server:
    port: 8081

spring:
  application:
    name: hello-security

logging:
  level:
    org:
      springframework:
        security: DEBUG
    example:
      hello_security: DEBUG

captcha:
  url: https://www.google.com/recaptcha/api/siteverify
  sitekey: 6Lc_qqoqAAAAAGlov3_Ks4zhJVz0z4T84BobSywK
  secret: 6Lc_qqoqAAAAAFIYXAZUf1uiMjOQf_BTAOhWzvx3