name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java JDK
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'

    # Step 3: Build with Maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml
