name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java JDK
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'

    # Step 3: Build with Maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: jeanlucien
        password: dckr_pat_pOqIqpnWectBvqdHhqKgUHkhjjI

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t jeanlucien/spring-basic-auth:latest .

    # Step 6: Push Docker image
    - name: Push Docker image
      run: |
        docker push jeanlucien/spring-basic-auth:latest
